---
ID: "88611f8b-8135-4ed2-8394-188615a0bb24"
Parent: "3b6709e6-fabc-4d11-b9bf-20cce7700544"
Template: "3b6709e6-fabc-4d11-b9bf-20cce7700544"
Path: /sitecore/templates/Feature/www/Tiles/Rendering Parameter/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230501T140207Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bbf0a684-3211-4da0-b7aa-94c6987fa6b1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230501T140207Z
